#!/bin/bash

# This is for my own convenience, edit it for your own environment.

PYTHON=python
$PYTHON setup.py build || exit 1

export PYTHONPATH=./build/lib.linux-x86_64-2.6
exec $PYTHON test_subprocess32.py
